name: web-scrapping
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.14
  - beautifulsoup4>=4.13.4,<5
  - requests>=2.32.3,<3
  - selenium>=4.32.0,<5
  - webdriver-manager>=4.0.2,<5
  - pytest>=8.3.5,<9
  - pytest-cov>=6.1.1,<7
  - pip>=25.1.1,<26
  - typer>=0.12.3,<1
  - unidecode>=1.3.8,<2
  - ruff>=0.11.10,<1